### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by xxidbr9** [xxidbr9/barnando-fullstack-interview-glints#15]
TODO

- [ ] Get All Favorite Restaurant
- [ ] User Accept To Collaborate
- [ ] Websocket For Listening data favorite
